apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: default
spec:
  acme:
    email: default
    server: default
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: default
            key: default