apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: seed
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - git:
      repoURL: ssh://git@github.com/mdmsua/tfc.git
      revision: HEAD
      directories:
        - path: charts/*
  template:
    metadata:
      name: "{{.path.basename}}"
    spec:
      project: default
      source:
        repoURL: ssh://git@github.com/mdmsua/tfc.git
        targetRevision: HEAD
        path: "{{.path.path}}"
        helm:
          valuesObject:
            domain: ${domain}
            externalSecrets:
              clientId: ${external_secrets_client_id}
              vaultUrl: ${key_vault_url}
              secretStoreName: azure
            cloudflare:
              remoteKey: ${cloudflare_remote_key}
              secretName: cloudflare
              apiTokenKey: api-token
            oidc:
              tenantId: ${oidc_tenant_id}
              clientId: ${oidc_client_id}
              groupId: ${oidc_group_id}
            envoyGateway:
              className: envoy-gateway
      destination:
        name: in-cluster
        namespace: "{{.path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PruneLast=true
