apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seed
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
  source:
    repoURL: ssh://git@github.com/mdmsua/tfc.git
    targetRevision: HEAD
    path: applications
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        domain: ${domain}
        registry: ${registry}
        externalSecrets:
          clientId: ${external_secrets_client_id}
          vaultUrl: ${key_vault_url}
        cloudflare:
          remoteKey: ${cloudflare_remote_key}
        oidc:
          tenantId: ${oidc_tenant_id}
          clientId: ${oidc_client_id}
          groupId: ${oidc_group_id}
        github:
          repository: ${github_repository}
          appIdRemoteKey: ${github_app_id_remote_key}
          appInstallationIdRemoteKey: ${github_app_installation_id_remote_key}
          appPemFileRemoteKey: ${github_app_pem_file_remote_key}
        storage:
          resourceGroup: ${storage_resource_group}
          storageAccount: ${storage_account_name}
          shareName: ${storage_share_name}
          folderName: ${storage_folder_name}
          server: ${storage_server}
          clientId: ${storage_client_id}
          volumeHandle: ${storage_volume_handle}
