apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://{{ .Values.domain }}/
  admin.enabled: false
  users.anonymous.enabled: false
  oidc.config: |
    name: Azure
    issuer: https://login.microsoftonline.com/{{ .Values.oidc.tenantId }}/v2.0
    clientID: {{ .Values.oidc.clientId }}
    azure:
      useWorkloadIdentity: true
    requestedIDTokenClaims:
      groups:
        essential: true
    requestedScopes:
      - openid
      - profile
      - email