apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://quay.io/jetstack/charts/cert-manager
      chart: cert-manager
      targetRevision: {{ .Values.certManager.version }}
      helm:
        valuesObject:
          crds:
            enabled: true
    - repoURL: ssh://git@github.com/mdmsua/tfc.git
      path: apps/templates/cert-manager
      targetRevision: HEAD
      helm:
        valuesObject:
          cloudflare: {{ .Values.cloudflare }}
          externalSecrets: {{ .Values.externalSecrets }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true