apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://quay.io/jetstack/charts/cert-manager
      chart: cert-manager
      targetRevision: {{ .Values.certManager.version }}
      helm:
        valuesObject:
          crds:
            enabled: true
    - repoURL: {{ .Values.spec.source }}
      targetRevision: HEAD
      path: apps/cert-manager
      kustomize:
        namespace: cert-manager
        patches:
          - target:
              kind: ClusterIssuer
              name: default
            patch: |-
              - op: replace
                path: /spec/acme/email
                value: {{ .Values.certManager.acme.email }}
              - op: replace
                path: /spec/acme/server
                value: {{ .Values.certManager.acme.server }}
              - op: replace
                path: /spec/acme/solvers/0/dns01/cloudflare/apiTokenSecretRef/name
                value: {{ .Values.cloudflare.secretName }}
              - op: replace
                path: /spec/acme/solvers/0/dns01/cloudflare/apiTokenSecretRef/key
                value: {{ .Values.cloudflare.apiTokenKey }}
          - target:
              kind: ExternalSecret
              name: default
            patch: |-
              - op: replace
                path: /spec/secretStoreRef/name
                value: {{ .Values.externalSecrets.secretStoreName }}
              - op: replace
                path: /spec/data/0/secretKey
                value: {{ .Values.cloudflare.apiTokenKey }}
              - op: replace
                path: /spec/data/0/remoteRef/key
                value: {{ .Values.cloudflare.remoteKey }}
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
