apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns
      chart: external-dns
      targetRevision: {{ .Values.externalDns.version }}
      helm:
        valuesObject:
          service:
            ipFamilyPolicy: PreferDualStack
            ipFamilies:
              - IPv4
              - IPv6
          deploymentStrategy:
            type: RollingUpdate
          provider:
            name: cloudflare
          env:
            - name: CF_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cloudflare.secretName }}
                  key: {{ .Values.cloudflare.apiTokenKey }}
    - repoURL: {{ .Values.spec.source }}
      targetRevision: HEAD
      path: apps/external-dns
      kustomize:
        namespace: external-dns
        patches:
          - target:
              kind: ExternalSecret
            patch: |-
              - op: replace
                path: /spec/secretStoreRef/name
                value: {{ .Values.externalSecrets.secretStoreName }}
              - op: replace
                path: /spec/data/0/secretKey
                value: {{ .Values.cloudflare.apiTokenKey }}
              - op: replace
                path: /spec/data/0/remoteRef/key
                value: {{ .Values.cloudflare.remoteKey }}
  destination:
    name: in-cluster
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true