apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: {{ .Values.externalDns.version }}
    helm:
      valuesObject:
        service:
          ipFamilyPolicy: PreferDualStack
          ipFamilies:
            - IPv4
            - IPv6
        deploymentStrategy:
          type: RollingUpdate
        provider:
          name: cloudflare
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.cloudflare.secretName }}
                key: {{ .Values.cloudflare.apiTokenKey }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.cloudflare.secretName }}
  namespace: external-dns
  labels:
    app.kubernetes.io/instance: external-dns
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  data:
    - secretKey: {{ .Values.cloudflare.apiTokenKey }}
      remoteRef:
        key: {{ .Values.cloudflare.remoteKey }}
  refreshPolicy: Periodic
  refreshInterval: 5m