apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: {{ .Values.externalSecrets.version }}
      helm:
        valuesObject:
          service:
            ipFamilyPolicy: PreferDualStack
            ipFamilies:
              - IPv4
              - IPv6
          serviceAccount:
            annotations:
              azure.workload.identity/client-id: {{ .Values.externalSecrets.clientId }}
          podLabels:
            azure.workload.identity/use: "true"
    - repoURL: {{ .Values.spec.source }}
      targetRevision: HEAD
      path: apps/external-secrets
      kustomize:
        namespace: external-secrets
        patches:
          - target:
              kind: ClusterSecretStore
            patch: |-
              - op: replace
                path: /metadata/name
                value: {{ .Values.externalSecrets.secretStoreName }}
              - op: replace
                path: /spec/provider/azurekv/vaultUrl
                value: {{ .Values.externalSecrets.vaultUrl }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true