apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare
spec:
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  data:
    - secretKey: default
      remoteRef:
        key: default
  refreshPolicy: Periodic
  refreshInterval: 5m
