apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    - PruneLast=true
  sources:
    - chart: argo-cd
      repoURL: ghcr.io/argoproj/argo-helm
      targetRevision: {{ .Values.argocd.version }}
      helm:
        valuesObject:
          global:
            domain: argocd.{{ .Values.domain }}
          notifications:
            enabled: false
          redis-ha:
            enabled: false
          repoServer:
            autoscaling:
              enabled: true
              minReplicas: 1
          configs:
            cm:
              admin.enabled: "false"
              users.anonymous.enabled: "false"
              oidc.config: |
                name: Azure
                issuer: https://login.microsoftonline.com/{{ .Values.oidc.tenantId }}/v2.0
                clientID: {{ .Values.oidc.clientId }}
                azure:
                  useWorkloadIdentity: true
                requestedIDTokenClaims:
                  groups:
                    essential: true
                requestedScopes:
                  - openid
                  - profile
                  - email
            rbac:
              policy.default: role:readonly
              policy.csv: |
                g, "{{ .Values.oidc.groupId }}", role:admin
          server:
            autoscaling:
              enabled: true
              minReplicas: 1
            podLabels:
              azure.workload.identity/use: "true"
            serviceAccount:
              annotations:
                azure.workload.identity/client-id: {{ .Values.oidc.clientId }}
            ingress:
              enabled: true
              tls: true
              ingressClassName: haproxy
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt
                haproxy.org/ssl-passthrough: "true"
                haproxy.org/ssl-redirect: "false"
                haproxy.org/backend-config-snippet: |
                  http-request set-var(txn.coraza.app) str(default)

                  filter spoe engine coraza config /usr/local/etc/haproxy/coraza.cfg
                  http-request send-spoe-group coraza request

                  http-request redirect code 302 location %[var(txn.coraza.data)] if { var(txn.coraza.action) -m str redirect }
                  http-response redirect code 302 location %[var(txn.coraza.data)] if { var(txn.coraza.action) -m str redirect }

                  http-request deny deny_status 403 hdr waf-block "request"  if { var(txn.coraza.action) -m str deny }
                  http-response deny deny_status 403 hdr waf-block "response" if { var(txn.coraza.action) -m str deny }

                  http-request silent-drop if { var(txn.coraza.action) -m str drop }
                  http-response silent-drop if { var(txn.coraza.action) -m str drop }

                  http-request deny deny_status 500 if { var(txn.coraza.error) -m int gt 0 }
                  http-response deny deny_status 500 if { var(txn.coraza.error) -m int gt 0 }
                
          