apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: echo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
  sources:
    - chart: raw
      repoURL: https://bedag.github.io/helm-charts/
      targetRevision: 2.0.2
      helm:
        valuesObject:
          resources:
          - apiVersion: v1
            kind: Pod
            metadata:
              name: echo
              labels:
                app: echo
            spec:
              containers:
              - name: echo
                image: hashicorp/http-echo:1.0
                ports:
                - name: http
                  containerPort: 5678
          - apiVersion: v1
            kind: Service
            metadata:
              name: echo
            spec:
              type: ClusterIP
              ipFamilyPolicy: PreferDualStack
              ipFamilies:
                - IPv4
                - IPv6
              selector:
                app: echo
              ports:
              - protocol: TCP
                port: 80
                targetPort: http
          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: echo
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt
                haproxy.org/ssl-redirect: "true"
            spec:
              ingressClassName: haproxy
              rules:
                - host: echo.{{ .Values.domain }}
                  http:
                    paths:
                      - path: /
                        pathType: Prefix
                        backend:
                          service:
                            name: echo
                            port:
                              number: 80
              tls:
                - hosts:
                    - echo.{{ .Values.domain }}
                  secretName: echo-tls

