apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: github-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    - CreateNamespace=true
    - PruneLast=true
  sources:
    - repoURL: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
      chart: gha-runner-scale-set-controller
      targetRevision: 0.13.1
      helm:
        releaseName: github
        valuesObject:
          image:
            repository: {{ .Values.registry }}/ghcr.io/actions/gha-runner-scale-set-controller
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          flags:
            watchSingleNamespace: github-runners
    - chart: raw
      repoURL: https://bedag.github.io/helm-charts/
      targetRevision: 2.0.2
      helm:
        valuesObject:
          resources:
            - apiVersion: v1
              kind: Namespace
              metadata:
                name: github-runners
            - apiVersion: external-secrets.io/v1
              kind: ExternalSecret
              metadata:
                name: app
                namespace: github-runners
              spec:
                secretStoreRef:
                  name: {{ .Values.externalSecrets.secretStoreName }}
                  kind: ClusterSecretStore
                data:
                  - secretKey: github_app_id
                    remoteRef:
                      key: {{ .Values.github.appIdRemoteKey }}
                      conversionStrategy: Default	
                      decodingStrategy: None
                      metadataPolicy: None
                  - secretKey: github_app_installation_id
                    remoteRef:
                      key: {{ .Values.github.appInstallationIdRemoteKey }}
                      conversionStrategy: Default	
                      decodingStrategy: None
                      metadataPolicy: None
                  - secretKey: github_app_private_key
                    remoteRef:
                      key: {{ .Values.github.appPemFileRemoteKey }}
                      conversionStrategy: Default	
                      decodingStrategy: None
                      metadataPolicy: None
                refreshPolicy: Periodic
                refreshInterval: 5m
            - apiVersion: external-secrets.io/v1
              kind: ExternalSecret
              metadata:
                name: storage
                namespace: github-runners
              spec:
                secretStoreRef:
                  name: {{ .Values.externalSecrets.secretStoreName }}
                  kind: ClusterSecretStore
                data:
                  - secretKey: azurestorageaccountname
                    remoteRef:
                      key: {{ .Values.storage.accountNameRemoteKey }}
                      conversionStrategy: Default	
                      decodingStrategy: None
                      metadataPolicy: None
                  - secretKey: azurestorageaccountkey
                    remoteRef:
                      key: {{ .Values.storage.accountKeyRemoteKey }}
                      conversionStrategy: Default	
                      decodingStrategy: None
                      metadataPolicy: None
                refreshPolicy: Periodic
                refreshInterval: 5m
            - apiVersion: v1
              kind: PersistentVolume
              metadata:
                name: github
              spec:
                capacity:
                  storage: 1Gi
                accessModes:
                  - ReadWriteMany
                persistentVolumeReclaimPolicy: Retain
                storageClassName: azurefile-csi-premium
                csi:
                  driver: file.csi.azure.com
                  volumeHandle: {{ .Values.storage.volumeHandle }}
                  volumeAttributes:
                    resourceGroup: {{ .Values.storage.resourceGroup }}
                    storageAccount: {{ .Values.storage.storageAccount }}
                    shareName: {{ .Values.storage.shareName }}
                    folderName: {{ .Values.storage.folderName }}
                    server: {{ .Values.storage.server }}
                    protocol: smb
                    secretName: storage
                mountOptions:
                  - dir_mode=0777
                  - file_mode=0777
                  - uid=1001
                  - gid=1001
                  - mfsymlinks
                  - cache=strict
                  - nosharesock
                  - nobrl
    - repoURL: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
      chart: gha-runner-scale-set
      targetRevision: 0.13.1
      helm:
        releaseName: github
        valuesObject:
          namespaceOverride: github-runners
          githubConfigUrl: {{ .Values.github.repository }}
          githubConfigSecret: app
          runnerScaleSetName: k8s
          containerMode:
            type: dind
          controllerServiceAccount:
           namespace: github-system
           name: github-gha-rs-controller
          template:
            spec:
              initContainers:
                - name: init-dind-externals
                  image: {{ .Values.registry }}/ghcr.io/actions/actions-runner:latest
                  command: ["cp", "-r", "/home/runner/externals/.", "/home/runner/tmpDir/"]
                  volumeMounts:
                    - name: dind-externals
                      mountPath: /home/runner/tmpDir
                - name: dind
                  image: {{ .Values.registry }}/docker.io/library/docker:dind-rootless
                  args:
                    - dockerd
                    - --host=unix:///var/run/docker.sock
                    - --group=$(DOCKER_GROUP_GID)
                  env:
                    - name: DOCKER_GROUP_GID
                      value: "123"
                  securityContext:
                    privileged: true
                  restartPolicy: Always
                  startupProbe:
                    exec:
                      command:
                        - docker
                        - info
                    initialDelaySeconds: 0
                    failureThreshold: 24
                    periodSeconds: 5
                  volumeMounts:
                    - name: work
                      mountPath: /home/runner/_work
                    - name: dind-sock
                      mountPath: /var/run
                    - name: dind-externals
                      mountPath: /home/runner/externals
              containers:
                - name: runner
                  image: {{ .Values.registry }}/ghcr.io/actions/actions-runner:latest
                  command: ["/home/runner/run.sh"]
                  env:
                    - name: DOCKER_HOST
                      value: unix:///var/run/docker.sock
                    - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
                      value: "120"
                  volumeMounts:
                    - name: work
                      mountPath: /home/runner/_work
                    - name: dind-sock
                      mountPath: /var/run
              volumes:
                - name: work
                  emptyDir: {}
                - name: dind-sock
                  emptyDir: {}
                - name: dind-externals
                  emptyDir: {}